#!/usr/bin/env python3
"""iteration 34 A2（外部レビュー E3）: standard profile は moat hook
（control-plane / destructive / secrets / deploy-gate）の *登録* を必須化する。

背景: check_framework_contract.run_profile_check は `required_hook_scripts` に
挙げた hook の settings 登録だけを検査する。standard は従来 3 つ（session-start /
check-gate / post-status-audit）しか required_hook_scripts に持たず、moat hook は
hooks_include（既定で install される）だが required ではなかったため、install 後に
moat hook の登録を消しても contract が PASS ＝ 登録ドリフト無検出だった。
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import tempfile
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]

# iter57: check-control-plane.sh 退役 → 残余静的ガード check-runtime-state.sh が
# runtime-state moat（主 moat は OS-lock だが、lock が守れない STATUS/settings
# 書込みはこの hook が担う＝登録ドリフト検出対象として維持）。
MOAT_HOOKS = [
    "check-runtime-state.sh",
    "check-destructive.sh",
    "check-secrets.sh",
    "check-deploy-gate.sh",
]


class TestStandardRequiresMoatHookScripts(unittest.TestCase):

    def test_standard_required_hook_scripts_includes_moat(self):
        """standard.json の required_hook_scripts が moat 4 hook を含む。"""
        path = ROOT / "templates" / "profiles" / "standard.json"
        data = json.loads(path.read_text(encoding="utf-8"))
        required = set(data.get("required_hook_scripts", []))
        for hook in MOAT_HOOKS:
            self.assertIn(
                f"hooks/{hook}", required,
                f"standard.json required_hook_scripts に hooks/{hook} が無い"
                f"（登録ドリフトが contract で無検出になる）",
            )


class TestRemovingMoatHookRegistrationFailsContract(unittest.TestCase):
    """standard install で moat hook の登録を消すと contract が FAIL する。"""

    @staticmethod
    def _settings_path(target: pathlib.Path) -> pathlib.Path:
        for name in ("settings.local.json", "settings.json"):
            p = target / ".claude" / name
            if p.exists():
                return p
        raise AssertionError("settings(.local).json not generated by setup.sh")

    @staticmethod
    def _contract(target: pathlib.Path) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["python3", str(ROOT / "scripts" / "check_framework_contract.py"),
             "--profile=standard", "--root", str(target)],
            capture_output=True, text=True,
        )

    def test_removing_each_moat_hook_registration_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = pathlib.Path(tmp) / "proj"
            r = subprocess.run(
                [str(ROOT / "bin" / "setup.sh"),
                 "--profile=standard", f"--target={target}"],
                capture_output=True, text=True,
            )
            self.assertEqual(r.returncode, 0, f"setup failed: {r.stdout}\n{r.stderr}")
            settings = self._settings_path(target)
            pristine = settings.read_text(encoding="utf-8")

            # 健全な standard scaffold は PASS（因果の固定）。
            r0 = self._contract(target)
            self.assertEqual(
                r0.returncode, 0,
                f"健全な standard install は PASS すべき: {r0.stdout}\n{r0.stderr}",
            )

            for hook in MOAT_HOOKS:
                with self.subTest(hook=hook):
                    data = json.loads(pristine)
                    for entries in data.get("hooks", {}).values():
                        if not isinstance(entries, list):
                            continue
                        for entry in entries:
                            if isinstance(entry, dict):
                                entry["hooks"] = [
                                    h for h in entry.get("hooks", [])
                                    if hook not in h.get("command", "")
                                ]
                    settings.write_text(json.dumps(data), encoding="utf-8")
                    r = self._contract(target)
                    self.assertNotEqual(
                        r.returncode, 0,
                        f"{hook} の登録を消したら contract は FAIL すべきだが PASS: "
                        f"{r.stdout}",
                    )
                    self.assertIn("missing hook registration", r.stdout)
                    settings.write_text(pristine, encoding="utf-8")  # restore


if __name__ == "__main__":
    unittest.main()
